all: src/main.cpp src/networkFunctions.cpp src/i2cFunctions.cpp src/data.cpp
	g++ -L /usr/include/boost -lboost_system -lpthread -o output src/main.cpp src/networkFunctions.cpp src/i2cFunctions.cpp src/data.cpp -I
